Train:
  batch_size: 128
  learning_rate: 0.1
  reg: 0.0005
  epochs: 50
  steps: [100, 101]
  warmup: 0
  momentum: 0.9
  gamma: 1

network:
  model: ResNet-32 # TwoLayerNet or VanillaCNN or MyModel or ResNet-32
  save_best: True

data:
  imbalance: imbalance # regular or imbalance
  beta: 0.9999

loss:
  loss_type: CE # CE or Focal

